# Project
version=2.0.1
group=net.bumblebee.csr
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Clay Soldiers Remake
mod_author=Bumble B33
mod_id=csr
license=MIT
credits=
description=A Data driven Remake of the Clay Soldier Mod.
wiki_link=https://bumble-b33.github.io/csr-wiki-v2/
issue_link=https://github.com/Bumble-B33/csr/issues
github_link=https://github.com/Bumble-B33/csr

minecraft_version_range=[26.1.2, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1


# Fabric
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.6

# NeoForge
neoforge_version=26.1.2.53-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

jei_version=29.6.2.31
jade_neo_version=26.1.1+neoforge
jade_fabric_version=26.1.0+fabric
modmenu_fabric_version=18.0.0-beta.1

accessories_version=1.4.3-beta
fabric_energy_version=5.0.0

curios_version=15.0.0-beta.2+26.1.2