package net.bumblebee.claysoldiers.platform;

import net.bumblebee.claysoldiers.ClaySoldiersCommon;
import net.bumblebee.claysoldiers.block.hamsterwheel.BatteryProperty;
import net.bumblebee.claysoldiers.config.ClientConfig;
import net.bumblebee.claysoldiers.config.CommonConfig;
import net.bumblebee.claysoldiers.config.ServerConfig;
import net.bumblebee.claysoldiers.platform.services.IConfig;
import net.neoforged.neoforge.common.ModConfigSpec;

public class NeoForgeConfig implements IConfig, ServerConfig, ClientConfig, CommonConfig {

    private static final ModConfigSpec.Builder SERVER_BUILDER = new ModConfigSpec.Builder();

    private static final ModConfigSpec.BooleanValue CLAY_SOLDIER_MENU_MODIFY = SERVER_BUILDER
            .comment("Whether the Inventory of a clay soldier can be edited via the menu. May cause loss of items.")
            .define(SOLDIER_MODIFY_MENU_KEY, false);
    private static final ModConfigSpec.LongValue HAMSTER_WHEEL_CAPACITY = SERVER_BUILDER
            .comment("Capacity of the Hamster Wheel")
            .defineInRange(HAMSTER_WHEEL_CAPACITY_KEY, 3000L, 1L, BatteryProperty.getMaxSupportedEnergy());
    private static final ModConfigSpec.IntValue HAMSTER_WHEEL_SPEED = SERVER_BUILDER
            .comment("Energy per Tick generated by the Hamster Wheel")
            .defineInRange(HAMSTER_WHEEL_SPEED_KEY, 3, 1, Integer.MAX_VALUE);
    private static final ModConfigSpec.BooleanValue SHEAR_BLADE_RECIPE = SERVER_BUILDER
            .comment("Enables/Disables the Crafting of Shear Blades from Shears")
            .define(SHEAR_BLADE_RECIPE_KEY, true);

    private static final ModConfigSpec.BooleanValue SOLDIER_DROP_INVENTORY = SERVER_BUILDER
            .comment("Whether Clay Soldiers should drop their Inventory on death")
            .define(SOLDIER_DROP_INVENTORY_KEY, true);

    private static final ModConfigSpec.DoubleValue SOLDIER_DROP_SELF = SERVER_BUILDER
            .comment("Chance for Clay Soldiers to drop them self")
            .defineInRange(SOLDIER_DROP_SELF_KEY, 0.5, 0, 1);

    private static final ModConfigSpec.BooleanValue CHIP_REQUIRES_LOYALTY = SERVER_BUILDER
            .comment("When true Chips can only be installed into Clay Soldiers loyal to the player")
            .define(CHIP_REQUIRES_LOYALTY_KEY, true);


    public static final ModConfigSpec SPEC = SERVER_BUILDER.build();

    private static final ModConfigSpec.Builder CLIENT_BUILDER = new ModConfigSpec.Builder();

    private static final ModConfigSpec.BooleanValue STAT_ITEM_SHOW_STATS = CLIENT_BUILDER
            .comment("Whether to show additional info when looking at a Clay Soldiers while holding a Statometer")
            .define(STATO_METER_SHOW_INFO_KEY, true);

    private static final ModConfigSpec.BooleanValue STAT_ITEM_SHOW_COUNT = CLIENT_BUILDER
            .comment("Whether to show the count of Clay Soldiers nearby when holding a Statometer")
            .define(STATO_METER_SHOW_COUNT_KEY, true);


    public static final ModConfigSpec CLIENT_SPEC = CLIENT_BUILDER.build();


    @Override
    public boolean soldierDropInventory() {
        return SOLDIER_DROP_INVENTORY.getAsBoolean();
    }

    @Override
    public float soldierDropSelf() {
        return (float) SOLDIER_DROP_SELF.getAsDouble();
    }

    @Override
    public boolean chipRequiresLoyalty() {
        return CHIP_REQUIRES_LOYALTY.getAsBoolean();
    }

    @Override
    public boolean canModifyClayMobMenu() {
        return CLAY_SOLDIER_MENU_MODIFY.getAsBoolean();
    }

    @Override
    public long getHamsterWheelEnergyCapacity() {
        return HAMSTER_WHEEL_CAPACITY.getAsLong();
    }

    @Override
    public long getHamsterWheelSpeed() {
        return HAMSTER_WHEEL_SPEED.getAsInt();
    }

    @Override
    public boolean statItemShowStats() {
        return STAT_ITEM_SHOW_STATS.getAsBoolean();
    }

    @Override
    public boolean statItemShowCount() {
        return STAT_ITEM_SHOW_COUNT.getAsBoolean();
    }

    @Override
    public boolean shearBladeRecipeEnabled() {
        try {
            return SHEAR_BLADE_RECIPE.getAsBoolean();
        } catch (IllegalStateException e) {
            ClaySoldiersCommon.ERROR_HANDLER.error("Trying to access ShearBlade Recipe Config: ", e);
            return true;
        }
    }

    @Override
    public ClientConfig getClientConfig() {
        return this;
    }

    @Override
    public ServerConfig getServerConfig() {
        return this;
    }

    @Override
    public CommonConfig getCommonConfig() {
        return this;
    }
}
